#!/usr/bin/env sh
#virtualenv /opt/octoprint
/opt/octoprint/bin/pip3 install OctoPrint
chown -R octoprint:root /opt/octoprint
. /home/octoprint/config/octoprint
haproxy -f /home/octoprint/config/haproxy.cfg -D
mjpg_streamer \
  -b \
  -i "input_uvc.so -r VGA -f 10 -timestamp -d /dev/${OC_VIDEO}" \
  -o "output_http.so -p 8080 -l 0.0.0.0 -w /usr/local/share/mjpg-streamer/www/www"
su -c "/opt/octoprint/bin/octoprint serve" octoprint
